declare function HuffCodeTab(len: any, max: any, tab: any, hl: any): void;
declare class HuffCodeTab {
    constructor(len: any, max: any, tab: any, hl: any);
    xlen: any;
    linmax: any;
    table: any;
    hlen: any;
}
export const t1HB: number[];
export const t2HB: number[];
export const t3HB: number[];
export const t5HB: number[];
export const t6HB: number[];
export const t7HB: number[];
export const t8HB: number[];
export const t9HB: number[];
export const t10HB: number[];
export const t11HB: number[];
export const t12HB: number[];
export const t13HB: number[];
export const t15HB: number[];
export const t16HB: number[];
export const t24HB: number[];
export const t32HB: number[];
export const t33HB: number[];
export const t1l: number[];
export const t2l: number[];
export const t3l: number[];
export const t5l: number[];
export const t6l: number[];
export const t7l: number[];
export const t8l: number[];
export const t9l: number[];
export const t10l: number[];
export const t11l: number[];
export const t12l: number[];
export const t13l: number[];
export const t15l: number[];
export const t16_5l: number[];
export const t16l: number[];
export const t24l: number[];
export const t32l: number[];
export const t33l: number[];
export const ht: HuffCodeTab[];
export const largetbl: number[];
export const table23: number[];
export const table56: number[];
export const bitrate_table: number[][];
export const samplerate_table: number[][];
export const scfsi_band: number[];
export {};
